'use strict';
const $=id=>document.getElementById(id);
let state=null,messages=[],channel='general',replyTo='',extraChannels=new Set(['general']),lastRender='',refreshBusy=false;
let noticeTimer,verifiedThisRun=false,threadParent=null;
let previousNetwork=null,networkEvents=[],onboardingPath="user";
const desktop=()=>window.go?.main?.Desktop;
function notice(text){$('notice').textContent=text;$('notice').hidden=false;clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>$('notice').hidden=true,6000)}
async function api(path,body){if(desktop())return JSON.parse(await desktop().Call(path,body===undefined?'':JSON.stringify(body)));const res=await fetch(path,{method:body===undefined?'GET':'POST',headers:body===undefined?{}:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const data=await res.json();if(!res.ok)throw new Error(data.error||'Request failed');return data}
function initials(name){return String(name||'?').split(/\s+/).slice(0,2).map(p=>p[0]||'').join('').toUpperCase()}
function el(tag,cls,text){const x=document.createElement(tag);if(cls)x.className=cls;if(text!==undefined)x.textContent=text;return x}
function busy(form,handler){form.addEventListener('submit',async e=>{e.preventDefault();const button=form.querySelector('button[type="submit"],button.primary,button.secondary');button.disabled=true;try{await handler()}catch(err){notice(err.message)}finally{button.disabled=false}})}
busy($('email-form'),async()=>{const r=await api('/api/auth/request',{email:$('email').value});$('email-form').hidden=true;$('code-form').hidden=false;if(r.devCode){$('dev-code').textContent='Local testing code: '+r.devCode;$('code').value=r.devCode}else{$('dev-code').textContent='Check your inbox. Codes expire after 10 minutes.'}$('code').focus()});
$('back-email').onclick=()=>{$('code-form').hidden=true;$('email-form').hidden=false};
busy($('code-form'),async()=>{await api('/api/auth/verify',{email:$('email').value,code:$('code').value,name:$('name').value});verifiedThisRun=true;$('code-form').hidden=true;$('workspace-step').hidden=false});
busy($('create-form'),async()=>{await api('/api/org/create',{name:$('org-name').value});await refresh()});
busy($('join-form'),async()=>{await api('/api/org/join',{invite:$('invite-code').value.trim()});await refresh()});
busy($('invite-form'),async()=>{const r=await api('/api/invites',{email:$('invite-email').value,kind:$('invite-kind').value});$('invite-output').value=r.invite;$('invite-result').hidden=false});
$('copy-invite').onclick=async()=>{try{await navigator.clipboard.writeText($('invite-output').value);notice('Invitation copied. Share it privately.')}catch{$('invite-output').select();notice('Select and copy the invitation.')}};
busy($('recovery-form'),async()=>{if(desktop()){await desktop().SaveRecovery($('recovery-password').value);$('recovery-password').value='';$('recovery-dialog').close();notice('Recovery export saved. Keep its passphrase separately.');return}const r=await fetch('/api/recovery/export',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:$('recovery-password').value})});if(!r.ok){const e=await r.json();throw new Error(e.error)}const blob=await r.blob();const url=URL.createObjectURL(blob);const a=el('a');a.href=url;a.download='radchat.recovery';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('recovery-password').value='';$('recovery-dialog').close();notice('Recovery export downloaded. Keep your passphrase separately.')});
busy($('channel-form'),async()=>{channel=$('new-channel').value;const policy=state.org.policy;await api('/api/org/policy',{retentionDays:policy.retentionDays,channels:[...policy.channels,{name:channel,description:''}]});await refresh();$('channel-dialog').close();lastRender='';renderChat();renderChannels()});
$('invite-button').onclick=()=>{$('invite-result').hidden=true;$('invite-dialog').showModal()};
for(const id of ['recovery-button','recovery-rail'])$(id).onclick=()=>$('recovery-dialog').showModal();
$('channel-button').onclick=()=>$('channel-dialog').showModal();
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());
$('menu-toggle').onclick=()=>$('sidebar').classList.toggle('open');
$('search').oninput=()=>{lastRender='';renderChat()};
$('cancel-reply').onclick=()=>{replyTo='';$('reply-banner').hidden=true};
async function send(){const text=$('message').value;if(!text.trim())return;const button=$('message-form').querySelector('button');button.disabled=true;try{const result=await api('/api/messages',{channel,text,replyTo});$('message').value='';replyTo='';$('reply-banner').hidden=true;await refresh();if(!result.propagated)notice('Stored on this device. Online peers will synchronize when connected.');$('messages').scrollTop=$('messages').scrollHeight}catch(e){notice(e.message)}finally{button.disabled=false}}
$('message-form').onsubmit=e=>{e.preventDefault();send()};
$('message').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();if(!$('message-form').querySelector('button').disabled)send()}};
function selectConversation(c){channel=c;replyTo='';$('reply-banner').hidden=true;lastRender='';renderChat();renderChannels();renderPeople();$('sidebar').classList.remove('open')}
function conversationName(c){if(!c.startsWith('dm:'))return c;return state?.org?.members?.find(m=>m.peer===c.slice(3))?.name||'Direct message'}
function renderChannels(){const nav=$('channels');nav.replaceChildren();for(const c of state.org.policy.channels){const b=el('button',c.name===channel?'active':'');b.append(el('span','hash','#'),document.createTextNode(c.name));b.onclick=()=>selectConversation(c.name);nav.append(b)}}
function renderPeople(){const members=state.org.members||[];$('people').replaceChildren();for(const m of members){const p=el('button','person'+(channel==='dm:'+m.peer?' selected':''));p.type='button';p.append(el('span','avatar '+(m.kind==='agent'?'agent':''),initials(m.name)),el('span','person-label',m.name+(m.peer===state.peer?' (you)':'')));const online=m.peer===state.peer||state.peers.some(p=>p.id===m.peer&&!p.bootstrap);const presence=el('span','presence-dot'+(online?' online':''));presence.title=online?'Connected to this device':'Not connected to this device';p.prepend(presence);if(m.kind==='agent')p.append(el('span','kind-badge','AGENT'));if(state.org.policy.deactivated[m.peer]){p.append(el('span','account-status','Deactivated'));p.classList.add('deactivated')}if(m.peer!==state.peer&&!state.org.policy.deactivated[m.peer]){p.title='Encrypted DM with '+m.name;p.onclick=()=>selectConversation('dm:'+m.peer)}else{p.disabled=true}$('people').append(p)}}
function renderChat(){if(!state?.org)return;const filtered=messages.filter(m=>m.channel===channel&&(!$("search").value||m.text.toLowerCase().includes($('search').value.toLowerCase())||m.name.toLowerCase().includes($('search').value.toLowerCase())));const key=JSON.stringify([channel,$('search').value,filtered]);if(key===lastRender)return;lastRender=key;const box=$('messages');const atBottom=box.scrollHeight-box.scrollTop-box.clientHeight<100;box.replaceChildren();const isDM=channel.startsWith('dm:'),label=conversationName(channel);$('channel-name').textContent=label;$('channel-name').previousElementSibling.textContent=isDM?'↗':'#';$('channel-description').textContent=isDM?'Only you and this person can decrypt these messages.':state.org.policy.channels.find(c=>c.name===channel)?.description||'A shared space for your people and agents.';$('message').placeholder=isDM?'Message '+label:'Message #'+label;$('composer-hint').textContent=isDM?'Pairwise encryption. Only the two of you.':'Your words. Your keys. Your network.';
 const welcome=el('div','channel-welcome');welcome.append(el('div','channel-icon',isDM?'↗':'#'),el('h2','',isDM?`Your conversation with ${label}`:`Welcome to #${label}`),el('p','',isDM?'Encrypted for just the two of you. DMs travel peer to peer and stay on your devices.':filtered.length?'A conversation shared by humans and agents. Encrypted on your network, stored on your devices.':'This is your team’s space. Say hello, share an idea, or bring an agent into the conversation.'));box.append(welcome);let day='';
 for(const m of filtered){const date=new Date(m.created),d=date.toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'});if(d!==day){box.append(el('div','day-divider',d));day=d}const row=el('article','message-row');row.append(el('div','avatar '+(m.kind==='agent'?'agent':''),initials(m.name)));const main=el('div','message-main');const meta=el('div','message-meta');meta.append(el('strong','',m.name));if(m.kind==='agent')meta.append(el('span','kind-badge','AGENT'));const time=el('time','',date.toLocaleTimeString(undefined,{hour:'numeric',minute:'2-digit'}));time.dateTime=date.toISOString();meta.append(time);main.append(meta);if(m.replyTo){const parent=messages.find(x=>x.id===m.replyTo);main.append(el('div','quoted-reply',parent?`↳ ${parent.name}: ${parent.text}`:'↳ Reply to an older message'))}main.append(el('p','message-text',m.text));row.append(main);const replies=messages.filter(x=>x.replyTo===m.id);const b=el('button','reply-button',replies.length?replies.length+' replies':'Reply');b.onclick=()=>{threadParent=m;renderThread();$('thread-dialog').showModal();$('thread-text').focus()};row.append(b);box.append(row)}if(atBottom)box.scrollTop=box.scrollHeight;
}
async function refresh(){if(refreshBusy)return;refreshBusy=true;try{state=await api('/api/state');if(state.org){$('onboarding').hidden=true;$('app').hidden=false;$('workspace-name').textContent=state.org.name;$('self-avatar').textContent=initials(state.name);$('invite-button').hidden=!state.org.owner;$('accounts-button').hidden=!state.org.owner;$('channel-button').hidden=!state.org.owner;$('retention-button').hidden=!state.org.owner;$('retention-label').textContent=state.org.policy.retentionDays===0?'Channel history: no age expiry':'Channel history: '+state.org.policy.retentionDays+' days';$('access-banner').hidden=Boolean(state.authorized);$('access-banner').textContent=state.deactivated?'Deactivated Account — your organization owner can reactivate your access.':'Waiting for fresh relay authorization. Your retained history is available locally.';$('message').disabled=!state.authorized;$('message-form').querySelector('button').disabled=!state.authorized;messages=state.deactivated?[]:await api('/api/messages');renderChannels();renderPeople();renderChat();const peers=state.peers.filter(p=>!p.bootstrap),relay=peers.filter(p=>p.relayed);$('peer-count').textContent=peers.length;$('relay-count').textContent=relay.length;renderNetwork();renderRunner();$('connection-details').textContent='Device: '+state.peer+'\n\n'+state.addresses.join('\n')}else if(state.email&&!verifiedThisRun){$('email').value=state.email;$('name').value=state.name;$('email-form').hidden=false;$('workspace-step').hidden=true;$('email-form').querySelector('button').firstChild.textContent='Verify email to continue '}if(state.startupError)notice(state.startupError)}catch(e){$('network-status').textContent='Device connection lost';notice(e.message)}finally{refreshBusy=false}}
$('retention-button').onclick=()=>{$('retention-days').value=state.org.policy.retentionDays;$('retention-dialog').showModal()};
busy($('retention-form'),async()=>{await api('/api/org/policy',{retentionDays:Number($('retention-days').value),channels:state.org.policy.channels});$('retention-dialog').close();await refresh();notice('Signed retention policy updated. Connected members will apply it.');});
$('settings-button').onclick=async()=>{if(!desktop()){notice('For a self-hosted relay, start the node with --auth and --bootstrap.');return}const c=await desktop().ConnectionSettings();$('settings-auth').value=c.auth;$('settings-bootstrap').value=c.bootstrap;$('settings-dialog').showModal()};
busy($('settings-form'),async()=>{await desktop().Configure($('settings-auth').value,$('settings-bootstrap').value);$('settings-dialog').close();await refresh();notice('Connected to your relay.');});
function renderAccounts(){const box=$('account-list');box.replaceChildren();for(const m of state.org.members){const row=el('div','account-row'),detail=el('div','account-detail');const inactive=Boolean(state.org.policy.deactivated[m.peer]);detail.append(el('strong','',m.name),el('small','',m.peer===state.peer?'Owner · You':inactive?'Deactivated Account':m.kind==='agent'?'Active agent':'Active member'));row.append(el('span','avatar '+(m.kind==='agent'?'agent':''),initials(m.name)),detail);if(m.peer!==state.peer){const b=el('button',inactive?'reactivate':'deactivate',inactive?'Reactivate':'Deactivate');b.onclick=async()=>{b.disabled=true;try{await api('/api/accounts',{peer:m.peer,active:inactive});await refresh();renderAccounts();notice(inactive?'Account reactivated with a new key grant.':'Account deactivated. Channel key rotated.')}catch(e){notice(e.message)}finally{b.disabled=false}};row.append(b)}box.append(row)}}
$('accounts-button').onclick=()=>{renderAccounts();$('accounts-dialog').showModal()};
$('account-retention').onclick=()=>{$('accounts-dialog').close();$('retention-button').click()};
$('account-recovery').onclick=()=>{$('accounts-dialog').close();$('recovery-dialog').showModal()};
function renderThread(){if(!threadParent)return;const box=$('thread-messages');box.replaceChildren();for(const m of [threadParent,...messages.filter(x=>x.replyTo===threadParent.id)]){const row=el('div','thread-row');row.append(el('strong','',m.name),el('p','message-text',m.text));box.append(row)}}
busy($('thread-form'),async()=>{if(!threadParent)return;await api('/api/messages',{channel:threadParent.channel,text:$('thread-text').value,replyTo:threadParent.id});$('thread-text').value='';await refresh();renderThread()});
function renderNetwork(){
 const peers=state.peers.filter(p=>!p.bootstrap),direct=peers.filter(p=>!p.relayed),relayed=peers.filter(p=>p.relayed);
 const roster=new Map(state.org.members.map(m=>[m.peer,m]));
 const current=new Map(peers.map(p=>[p.id,p]));
 const addEvent=(id,verb)=>{const member=roster.get(id);if(!member)return;networkEvents.unshift({text:member.name+' '+verb,time:new Date()});networkEvents=networkEvents.slice(0,12);notice(member.name+' '+verb)};
 if(previousNetwork&&previousNetwork.org===state.org.id){for(const [id] of current)if(!previousNetwork.peers.has(id))addEvent(id,'connected to your network');for(const [id] of previousNetwork.peers)if(!current.has(id))addEvent(id,'disconnected from your device');for(const [id,m] of roster)if(!previousNetwork.members.has(id)&&id!==state.peer)addEvent(id,'joined the workspace')}
 previousNetwork={org:state.org.id,peers:current,members:roster};
 const bootstrap=state.peers.some(p=>p.bootstrap);
 $('network-status').textContent=peers.length?`● P2P · ${direct.length} direct · ${relayed.length} relayed`:bootstrap?'● Relay connected · awaiting teammates':'○ Connecting to your relay';
 $('network-status').classList.toggle('connected',bootstrap||peers.length>0);
 document.querySelector('.mesh-visual').classList.toggle('mesh-connected',peers.length>0);
 $('network-connections').replaceChildren();
 const row=(name,label,online)=>{const r=el('div','connection-row');r.append(el('span','presence-dot'+(online?' online':'')),el('strong','',name),el('small','',label));return r};
 $('network-connections').append(row('Your device','Encrypted identity active',true),row('Bootstrap relay',bootstrap?'Connected · discovery & encrypted forwarding':'Not connected',bootstrap));
 for(const m of state.org.members){if(m.peer===state.peer)continue;const p=current.get(m.peer);$('network-connections').append(row(m.name,state.org.policy.deactivated[m.peer]?'Deactivated':p?p.relayed?'P2P via encrypted relay':'Direct P2P':'Not connected to this device',Boolean(p)))}
 for(const id of ['network-feed','network-activity']){const box=$(id);box.replaceChildren();for(const event of networkEvents.slice(0,id==='network-feed'?3:12)){const item=el('div','network-event');item.append(el('span','',event.text),el('time','',event.time.toLocaleTimeString(undefined,{hour:'numeric',minute:'2-digit'})));box.append(item)}if(!networkEvents.length)box.append(el('p','subtle','New connections and workspace joins will appear here.'))}
 const agents=$('agent-connections');agents.replaceChildren();for(const m of state.org.members.filter(m=>m.kind==='agent')){const p=current.get(m.peer);agents.append(row(m.name,p?'Connected · loop status not reported':'Waiting for agent connection',Boolean(p)))}if(!agents.childElementCount)agents.append(el('p','subtle','No agent nodes have joined yet.'));
}
$('network-status').onclick=()=>$('network-dialog').showModal();
function choosePath(path){onboardingPath=path;$('path-user').classList.toggle('selected',path==='user');$('path-contributor').classList.toggle('selected',path==='contributor');$('path-explanation').textContent=path==='contributor'?'Bring a model key to your native runner. Launch a bounded agent, then build its skills.':'Start with your private workspace. Service discovery and checkout are coming next.'}
$('path-user').onclick=()=>choosePath('user');$('path-contributor').onclick=()=>choosePath('contributor');
$('contributor-button').onclick=()=>{const browser=state.runtime==='browser';$('browser-runner-guide').hidden=!browser;$('runner-form').hidden=browser;$('runner-channel').replaceChildren();for(const c of state.org.policy.channels){const option=el('option','',c.name);option.value=c.name;$('runner-channel').append(option)}renderRunner();$('contributor-dialog').showModal()};
busy($('runner-form'),async()=>{const key=$('runner-key').value;try{await api('/api/runner',{action:'start',name:$('runner-name').value,config:{provider:$('runner-provider').value,model:$('runner-model').value,apiKey:key,prompt:$('runner-prompt').value,channel:$('runner-channel').value,interval:Number($('runner-interval').value),limit:Number($('runner-limit').value),consent:$('runner-consent').checked}});notice('Native agent enrolled. Watching its actual loop state.');await refresh()}finally{$('runner-key').value=''}});
function renderRunner(){const r=state.runner,box=$('runner-indicator');box.replaceChildren();if(!r||r.phase==='not-configured')return;const label={listening:'Listening for next iteration',working:'Calling model provider','awaiting-approval':'Output needs your approval',paused:'Paused',failed:'Needs attention',completed:'Call limit reached','setting-up':'Setting up native agent',stopped:'Stopped'}[r.phase]||r.phase;box.append(el('span','runner-light '+r.phase),el('strong','',label),el('small','',`${r.calls}/${r.limit} model calls`));$('runner-review').hidden=false;$('runner-phase').textContent=label;$('runner-error').textContent=r.error||'';$('runner-output').textContent=r.pending||'';$('runner-approve').hidden=r.phase!=='awaiting-approval';$('runner-stop').hidden=['paused','stopped','completed'].includes(r.phase)}
$('runner-stop').onclick=async()=>{try{await api('/api/runner',{action:'stop'});await refresh();notice('Agent paused. Any in-flight model request was cancelled.')}catch(e){notice(e.message)}};
$('runner-approve').onclick=async()=>{const b=$('runner-approve');b.disabled=true;try{await api('/api/runner',{action:'approve'});await refresh()}catch(e){notice(e.message)}finally{b.disabled=false}};
async function showEconomy(){$('economy-dialog').showModal();try{const s=await api('/api/economy');$('economy-status').textContent=s.connected?'● Connected to Solana '+s.cluster:'○ '+(s.error||'Test network unavailable');const box=$('economy-details');box.replaceChildren();box.append(el('p','',s.connected?'Verified cluster · slot '+s.slot:'RPC: '+s.rpc));if(s.genesis)box.append(el('small','connection-details','Genesis: '+s.genesis));$('economy-explorer').href='https://explorer.solana.com/?cluster='+s.cluster;$('economy-explorer').textContent='Explore Solana '+s.cluster+' ↗'}catch(e){$('economy-status').textContent=e.message}}
$('economy-button').onclick=showEconomy;$('economy-sidebar').onclick=showEconomy;
refresh();setInterval(refresh,2500);
